# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'appealStatusesWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem


class Ui_appealStatusesWindow(object):
    def setupUi(self, appealStatusesWindow):
        appealStatusesWindow.setObjectName("appealStatusesWindow")
        appealStatusesWindow.resize(900, 700)
        self.startLabel = QtWidgets.QLabel(appealStatusesWindow)
        self.startLabel.setGeometry(QtCore.QRect(0, 0, 901, 100))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.startLabel.setFont(font)
        self.startLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.startLabel.setAutoFillBackground(False)
        self.startLabel.setStyleSheet("")
        self.startLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.startLabel.setWordWrap(False)
        self.startLabel.setObjectName("startLabel")
        self.backButton = QtWidgets.QPushButton(appealStatusesWindow)
        self.backButton.setGeometry(QtCore.QRect(10, 20, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("")
        self.backButton.setDefault(False)
        self.backButton.setFlat(False)
        self.backButton.setObjectName("backButton")
        self.tableAppealStatusesWidget = QtWidgets.QTableWidget(appealStatusesWindow)
        self.tableAppealStatusesWidget.setGeometry(QtCore.QRect(50, 190, 800, 350))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.tableAppealStatusesWidget.setFont(font)
        self.tableAppealStatusesWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableAppealStatusesWidget.setObjectName("tableAppealStatusesWidget")
        self.tableAppealStatusesWidget.setColumnCount(0)
        self.tableAppealStatusesWidget.setRowCount(0)

        self.backButton.clicked.connect(backWindowShow)

        from WorkWithDB import callAppealStatusesInfo
        statusNameAppeal = callAppealStatusesInfo()

        self.tableAppealStatusesWidget.setRowCount(len(statusNameAppeal))
        self.tableAppealStatusesWidget.setColumnCount(1)
        self.tableAppealStatusesWidget.setHorizontalHeaderLabels(('Статус', ''))
        self.tableAppealStatusesWidget.setColumnWidth(0, 800)

        for i in range(len(statusNameAppeal)):
            self.tableAppealStatusesWidget.setItem(i, 0, QTableWidgetItem(str(statusNameAppeal[i][0])))

        self.retranslateUi(appealStatusesWindow)
        QtCore.QMetaObject.connectSlotsByName(appealStatusesWindow)

    def retranslateUi(self, appealStatusesWindow):
        _translate = QtCore.QCoreApplication.translate
        appealStatusesWindow.setWindowTitle(_translate("appealStatusesWindow", "Dialog"))
        self.startLabel.setText(_translate("appealStatusesWindow", "Статус заявок"))
        self.backButton.setText(_translate("appealStatusesWindow", "Назад"))


def backWindowShow():
    from QtWindows.menuWindows import showMenuWindow
    showMenuWindow()
    closeAppealStatusesWindow()


def showAppealStatusesWindow():
    global appealStatusesWindow
    appealStatusesWindow = QtWidgets.QDialog()
    ui = Ui_appealStatusesWindow()
    ui.setupUi(appealStatusesWindow)
    appealStatusesWindow.show()


def closeAppealStatusesWindow():
    appealStatusesWindow.close()
