# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'authorizationWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_authorizationWindow(object):
    def setupUi(self, authorizationWindow):
        authorizationWindow.setObjectName("authorizationWindow")
        authorizationWindow.resize(900, 700)
        self.startLabel = QtWidgets.QLabel(authorizationWindow)
        self.startLabel.setGeometry(QtCore.QRect(0, 0, 901, 100))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.startLabel.setFont(font)
        self.startLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.startLabel.setAutoFillBackground(False)
        self.startLabel.setStyleSheet("")
        self.startLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.startLabel.setWordWrap(False)
        self.startLabel.setObjectName("startLabel")
        self.loginLabel = QtWidgets.QLabel(authorizationWindow)
        self.loginLabel.setGeometry(QtCore.QRect(240, 180, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.loginLabel.setFont(font)
        self.loginLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.loginLabel.setAutoFillBackground(False)
        self.loginLabel.setStyleSheet("")
        self.loginLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.loginLabel.setWordWrap(False)
        self.loginLabel.setObjectName("loginLabel")
        self.passLabel = QtWidgets.QLabel(authorizationWindow)
        self.passLabel.setGeometry(QtCore.QRect(240, 290, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.passLabel.setFont(font)
        self.passLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.passLabel.setAutoFillBackground(False)
        self.passLabel.setStyleSheet("")
        self.passLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.passLabel.setWordWrap(False)
        self.passLabel.setObjectName("passLabel")
        self.loginLineEdit = QtWidgets.QLineEdit(authorizationWindow)
        self.loginLineEdit.setGeometry(QtCore.QRect(240, 240, 460, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.loginLineEdit.setFont(font)
        self.loginLineEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.loginLineEdit.setTabletTracking(True)
        self.loginLineEdit.setStyleSheet("border-color: rgb(0, 85, 0);")
        self.loginLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.loginLineEdit.setObjectName("loginLineEdit")
        self.passwordLineEdit = QtWidgets.QLineEdit(authorizationWindow)
        self.passwordLineEdit.setGeometry(QtCore.QRect(240, 350, 460, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.passwordLineEdit.setFont(font)
        self.passwordLineEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.passwordLineEdit.setTabletTracking(True)
        self.passwordLineEdit.setStyleSheet("border-color: rgb(0, 85, 0);")
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.inputButton = QtWidgets.QPushButton(authorizationWindow)
        self.inputButton.setGeometry(QtCore.QRect(370, 450, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.inputButton.setFont(font)
        self.inputButton.setStyleSheet("")
        self.inputButton.setDefault(False)
        self.inputButton.setFlat(False)
        self.inputButton.setObjectName("inputButton")
        self.registrationInputButton = QtWidgets.QPushButton(authorizationWindow)
        self.registrationInputButton.setGeometry(QtCore.QRect(640, 120, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.registrationInputButton.setFont(font)
        self.registrationInputButton.setStyleSheet("")
        self.registrationInputButton.setDefault(False)
        self.registrationInputButton.setFlat(False)
        self.registrationInputButton.setObjectName("registrationInputButton")

        self.registrationInputButton.clicked.connect(registration)
        self.inputButton.clicked.connect(lambda:  testParam(self.loginLineEdit.text(), self.passwordLineEdit.text()))

        self.retranslateUi(authorizationWindow)
        QtCore.QMetaObject.connectSlotsByName(authorizationWindow)

    def retranslateUi(self, authorizationWindow):
        _translate = QtCore.QCoreApplication.translate
        authorizationWindow.setWindowTitle(_translate("authorizationWindow", "Dialog"))
        self.startLabel.setText(_translate("authorizationWindow", "Вход"))
        self.loginLabel.setText(_translate("authorizationWindow", "Введите логин:"))
        self.passLabel.setText(_translate("authorizationWindow", "Введите пароль:"))
        self.loginLineEdit.setPlaceholderText(_translate("authorizationWindow", "Пример: ivanov_ivan"))
        self.passwordLineEdit.setPlaceholderText(_translate("authorizationWindow", "Пример: 1234"))
        self.inputButton.setText(_translate("authorizationWindow", "Войти"))
        self.registrationInputButton.setText(_translate("authorizationWindow", "Зарегистрироваться"))


def registration():
    from QtWindows.registrationWindow import showRegistrationWindow
    showRegistrationWindow()
    closeMainWindow()


def testParam(login, password):
    from InputTest import authorizationParamTest
    authorizationParamTest(login, password)


def start():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    global authorizationWindow
    authorizationWindow = QtWidgets.QDialog()
    ui = Ui_authorizationWindow()
    ui.setupUi(authorizationWindow)
    authorizationWindow.show()
    sys.exit(app.exec_())


def showAuthorizationWindow():
    global authorizationWindow
    authorizationWindow = QtWidgets.QMainWindow()
    ui = Ui_authorizationWindow()
    ui.setupUi(authorizationWindow)
    authorizationWindow.show()


def closeMainWindow():
    authorizationWindow.close()
