# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'certificationLevelsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem


class Ui_certificationLevelsWindow(object):
    def setupUi(self, certificationLevelsWindow):
        certificationLevelsWindow.setObjectName("certificationLevelsWindow")
        certificationLevelsWindow.resize(900, 700)
        self.startLabel = QtWidgets.QLabel(certificationLevelsWindow)
        self.startLabel.setGeometry(QtCore.QRect(0, 0, 901, 100))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.startLabel.setFont(font)
        self.startLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.startLabel.setAutoFillBackground(False)
        self.startLabel.setStyleSheet("")
        self.startLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.startLabel.setWordWrap(False)
        self.startLabel.setObjectName("startLabel")
        self.backButton = QtWidgets.QPushButton(certificationLevelsWindow)
        self.backButton.setGeometry(QtCore.QRect(10, 20, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("")
        self.backButton.setDefault(False)
        self.backButton.setFlat(False)
        self.backButton.setObjectName("backButton")
        self.certificationLevelsWidget = QtWidgets.QTableWidget(certificationLevelsWindow)
        self.certificationLevelsWidget.setGeometry(QtCore.QRect(50, 190, 800, 350))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.certificationLevelsWidget.setFont(font)
        self.certificationLevelsWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.certificationLevelsWidget.setObjectName("certificationLevelsWidget")
        self.certificationLevelsWidget.setColumnCount(0)
        self.certificationLevelsWidget.setRowCount(0)

        self.backButton.clicked.connect(backWindowShow)

        from WorkWithDB import callCertificationLevelsInfo
        statusNameAppeal = callCertificationLevelsInfo()

        self.certificationLevelsWidget.setRowCount(len(statusNameAppeal))
        self.certificationLevelsWidget.setColumnCount(2)
        self.certificationLevelsWidget.setHorizontalHeaderLabels(('Код уровня', 'Уровень', ''))
        self.certificationLevelsWidget.setColumnWidth(0, 150)
        self.certificationLevelsWidget.setColumnWidth(1, 624)

        for i in range(len(statusNameAppeal)):
            self.certificationLevelsWidget.setItem(i, 0, QTableWidgetItem(str(statusNameAppeal[i][0])))
            self.certificationLevelsWidget.setItem(i, 1, QTableWidgetItem(str(statusNameAppeal[i][1])))

        self.retranslateUi(certificationLevelsWindow)
        QtCore.QMetaObject.connectSlotsByName(certificationLevelsWindow)

    def retranslateUi(self, certificationLevelsWindow):
        _translate = QtCore.QCoreApplication.translate
        certificationLevelsWindow.setWindowTitle(_translate("certificationLevelsWindow", "Dialog"))
        self.startLabel.setText(_translate("certificationLevelsWindow", "Уровни сертификации"))
        self.backButton.setText(_translate("certificationLevelsWindow", "Назад"))


def backWindowShow():
    from QtWindows.menuWindows import showMenuWindow
    showMenuWindow()
    closeCertificationLevelsWindow()


def showCertificationLevelsWindow():
    global certificationLevelsWindow
    certificationLevelsWindow = QtWidgets.QDialog()
    ui = Ui_certificationLevelsWindow()
    ui.setupUi(certificationLevelsWindow)
    certificationLevelsWindow.show()


def closeCertificationLevelsWindow():
    certificationLevelsWindow.close()
