# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'okno.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_inputParamProcedureWindow(object):
    def setupUi(self, inputParamProcedureWindow):
        inputParamProcedureWindow.setObjectName("inputParamProcedureWindow")
        inputParamProcedureWindow.resize(900, 700)
        self.startLabel = QtWidgets.QLabel(inputParamProcedureWindow)
        self.startLabel.setGeometry(QtCore.QRect(0, 0, 901, 100))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.startLabel.setFont(font)
        self.startLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.startLabel.setAutoFillBackground(False)
        self.startLabel.setStyleSheet("")
        self.startLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.startLabel.setWordWrap(False)
        self.startLabel.setObjectName("startLabel")
        self.passLabel = QtWidgets.QLabel(inputParamProcedureWindow)
        self.passLabel.setGeometry(QtCore.QRect(150, 230, 521, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.passLabel.setFont(font)
        self.passLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.passLabel.setAutoFillBackground(False)
        self.passLabel.setStyleSheet("")
        self.passLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.passLabel.setWordWrap(False)
        self.passLabel.setObjectName("passLabel")
        self.levelLineEdit = QtWidgets.QLineEdit(inputParamProcedureWindow)
        self.levelLineEdit.setGeometry(QtCore.QRect(150, 290, 600, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.levelLineEdit.setFont(font)
        self.levelLineEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.levelLineEdit.setTabletTracking(True)
        self.levelLineEdit.setStyleSheet("border-color: rgb(0, 85, 0);")
        self.levelLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.levelLineEdit.setObjectName("levelLineEdit")
        self.inputButton = QtWidgets.QPushButton(inputParamProcedureWindow)
        self.inputButton.setGeometry(QtCore.QRect(350, 510, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.inputButton.setFont(font)
        self.inputButton.setStyleSheet("")
        self.inputButton.setDefault(False)
        self.inputButton.setFlat(False)
        self.inputButton.setObjectName("inputButton")
        self.backButton = QtWidgets.QPushButton(inputParamProcedureWindow)
        self.backButton.setGeometry(QtCore.QRect(10, 90, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("")
        self.backButton.setDefault(False)
        self.backButton.setFlat(False)
        self.backButton.setObjectName("backButton")
        self.passLabel_2 = QtWidgets.QLabel(inputParamProcedureWindow)
        self.passLabel_2.setGeometry(QtCore.QRect(150, 350, 521, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.passLabel_2.setFont(font)
        self.passLabel_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.passLabel_2.setAutoFillBackground(False)
        self.passLabel_2.setStyleSheet("")
        self.passLabel_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.passLabel_2.setWordWrap(False)
        self.passLabel_2.setObjectName("passLabel_2")
        self.levelLineEdit_2 = QtWidgets.QLineEdit(inputParamProcedureWindow)
        self.levelLineEdit_2.setGeometry(QtCore.QRect(150, 410, 600, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.levelLineEdit_2.setFont(font)
        self.levelLineEdit_2.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.levelLineEdit_2.setTabletTracking(True)
        self.levelLineEdit_2.setStyleSheet("border-color: rgb(0, 85, 0);")
        self.levelLineEdit_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.levelLineEdit_2.setObjectName("levelLineEdit_2")

        self.backButton.clicked.connect(backWindowShow)
        self.inputButton.clicked.connect(lambda: fill_certification_level(self.levelLineEdit.text(), self.levelLineEdit_2.text()))

        self.retranslateUi(inputParamProcedureWindow)
        QtCore.QMetaObject.connectSlotsByName(inputParamProcedureWindow)

    def retranslateUi(self, inputParamProcedureWindow):
        _translate = QtCore.QCoreApplication.translate
        inputParamProcedureWindow.setWindowTitle(_translate("inputParamProcedureWindow", "Dialog"))
        self.startLabel.setText(_translate("inputParamProcedureWindow", "Новый уровень сертификации"))
        self.passLabel.setText(_translate("inputParamProcedureWindow", "Введите номер уровня"))
        self.levelLineEdit.setPlaceholderText(_translate("inputParamProcedureWindow", "Пример: 1"))
        self.inputButton.setText(_translate("inputParamProcedureWindow", "Далее"))
        self.backButton.setText(_translate("inputParamProcedureWindow", "Назад"))
        self.passLabel_2.setText(_translate("inputParamProcedureWindow", "Введите название уровня"))
        self.levelLineEdit_2.setPlaceholderText(_translate("inputParamProcedureWindow", "Пример: Базовый"))


def backWindowShow():
    from QtWindows.menuWindows import showMenuWindow
    showMenuWindow()
    closeInputParamProcedureWindow()


def fill_certification_level(desc, priority):
    from WorkWithDB import fill_certification_level
    fill_certification_level(desc, priority)
    msgBox = QMessageBox()
    msgBox.setText("Уровень добавлен")
    msgBox.exec_()
    pass

def show_fill_certification_level_Window():
    global show_fill_certification_level_Window
    show_fill_certification_level_Window = QtWidgets.QDialog()
    ui = Ui_inputParamProcedureWindow()
    ui.setupUi(show_fill_certification_level_Window)
    show_fill_certification_level_Window.show()


def closeInputParamProcedureWindow():
    show_fill_certification_level_Window.close()