# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menuWindows.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_menuWindow(object):
    def setupUi(self, menuWindow):
        menuWindow.setObjectName("menuWindow")
        menuWindow.resize(900, 700)
        self.startLabel = QtWidgets.QLabel(menuWindow)
        self.startLabel.setGeometry(QtCore.QRect(0, 0, 901, 100))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.startLabel.setFont(font)
        self.startLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.startLabel.setAutoFillBackground(False)
        self.startLabel.setStyleSheet("")
        self.startLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.startLabel.setWordWrap(False)
        self.startLabel.setObjectName("startLabel")
        self.appealStatusesButton = QtWidgets.QPushButton(menuWindow)
        self.appealStatusesButton.setGeometry(QtCore.QRect(100, 180, 290, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.appealStatusesButton.setFont(font)
        self.appealStatusesButton.setStyleSheet("")
        self.appealStatusesButton.setDefault(False)
        self.appealStatusesButton.setFlat(False)
        self.appealStatusesButton.setObjectName("appealStatusesButton")
        self.backButton = QtWidgets.QPushButton(menuWindow)
        self.backButton.setGeometry(QtCore.QRect(10, 20, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("")
        self.backButton.setDefault(False)
        self.backButton.setFlat(False)
        self.backButton.setObjectName("backButton")
        self.appStatusesButton = QtWidgets.QPushButton(menuWindow)
        self.appStatusesButton.setGeometry(QtCore.QRect(550, 180, 290, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.appStatusesButton.setFont(font)
        self.appStatusesButton.setStyleSheet("")
        self.appStatusesButton.setDefault(False)
        self.appStatusesButton.setFlat(False)
        self.appStatusesButton.setObjectName("appStatusesButton")
        self.certificationLevelsButton = QtWidgets.QPushButton(menuWindow)
        self.certificationLevelsButton.setGeometry(QtCore.QRect(100, 270, 290, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.certificationLevelsButton.setFont(font)
        self.certificationLevelsButton.setStyleSheet("")
        self.certificationLevelsButton.setDefault(False)
        self.certificationLevelsButton.setFlat(False)
        self.certificationLevelsButton.setObjectName("certificationLevelsButton")
        self.fill_appeal_statuses = QtWidgets.QPushButton(menuWindow)
        self.fill_appeal_statuses.setGeometry(QtCore.QRect(550, 270, 290, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.fill_appeal_statuses.setFont(font)
        self.fill_appeal_statuses.setStyleSheet("")
        self.fill_appeal_statuses.setDefault(False)
        self.fill_appeal_statuses.setFlat(False)
        self.fill_appeal_statuses.setObjectName("fill_appeal_statuses")
        self.fill_app_statuses = QtWidgets.QPushButton(menuWindow)
        self.fill_app_statuses.setGeometry(QtCore.QRect(550, 360, 290, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.fill_app_statuses.setFont(font)
        self.fill_app_statuses.setStyleSheet("")
        self.fill_app_statuses.setDefault(False)
        self.fill_app_statuses.setFlat(False)
        self.fill_app_statuses.setObjectName("fill_app_statuses")
        self.delete_appeal_statuses = QtWidgets.QPushButton(menuWindow)
        self.delete_appeal_statuses.setGeometry(QtCore.QRect(100, 360, 290, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.delete_appeal_statuses.setFont(font)
        self.delete_appeal_statuses.setStyleSheet("")
        self.delete_appeal_statuses.setDefault(False)
        self.delete_appeal_statuses.setFlat(False)
        self.delete_appeal_statuses.setObjectName("delete_appeal_statuses")
        self.delete_app_statuses = QtWidgets.QPushButton(menuWindow)
        self.delete_app_statuses.setGeometry(QtCore.QRect(100, 450, 290, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.delete_app_statuses.setFont(font)
        self.delete_app_statuses.setStyleSheet("")
        self.delete_app_statuses.setDefault(False)
        self.delete_app_statuses.setFlat(False)
        self.delete_app_statuses.setObjectName("delete_app_statuses")
        self.fill_certification_level = QtWidgets.QPushButton(menuWindow)
        self.fill_certification_level.setGeometry(QtCore.QRect(550, 450, 290, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.fill_certification_level.setFont(font)
        self.fill_certification_level.setStyleSheet("")
        self.fill_certification_level.setDefault(False)
        self.fill_certification_level.setFlat(False)
        self.fill_certification_level.setObjectName("fill_certification_level")
        self.delete_certification_level = QtWidgets.QPushButton(menuWindow)
        self.delete_certification_level.setGeometry(QtCore.QRect(550, 540, 290, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.delete_certification_level.setFont(font)
        self.delete_certification_level.setStyleSheet("")
        self.delete_certification_level.setDefault(False)
        self.delete_certification_level.setFlat(False)
        self.delete_certification_level.setObjectName("delete_certification_level")
        self.fill_problem_types = QtWidgets.QPushButton(menuWindow)
        self.fill_problem_types.setGeometry(QtCore.QRect(100, 540, 290, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.fill_problem_types.setFont(font)
        self.fill_problem_types.setStyleSheet("")
        self.fill_problem_types.setDefault(False)
        self.fill_problem_types.setFlat(False)
        self.fill_problem_types.setObjectName("change_cert_level_desc")

        self.backButton.clicked.connect(backWindowShow)
        self.appealStatusesButton.clicked.connect(appealStatuses)
        self.appStatusesButton.clicked.connect(appStatuses)
        self.certificationLevelsButton.clicked.connect(certificationLevels)
        self.fill_appeal_statuses.clicked.connect(fill_appeal_statuses)
        self.delete_appeal_statuses.clicked.connect(delete_appeal_statuses)
        self.fill_app_statuses.clicked.connect(fill_app_statuses)
        self.delete_app_statuses.clicked.connect(delete_app_statuses)
        self.fill_problem_types.clicked.connect(fill_problem_types)
        self.fill_certification_level.clicked.connect(fill_certification_level)
        self.delete_certification_level.clicked.connect(delete_problem_type)

        self.retranslateUi(menuWindow)
        QtCore.QMetaObject.connectSlotsByName(menuWindow)

    def retranslateUi(self, menuWindow):
        _translate = QtCore.QCoreApplication.translate
        menuWindow.setWindowTitle(_translate("menuWindow", "Dialog"))
        self.startLabel.setText(_translate("menuWindow", "Меню"))
        self.appealStatusesButton.setText(_translate("menuWindow", "Статус заявок"))
        self.backButton.setText(_translate("menuWindow", "Выйти"))
        self.appStatusesButton.setText(_translate("menuWindow", "Статус приложения"))
        self.certificationLevelsButton.setText(_translate("menuWindow", "Уровни сертификации"))
        self.fill_appeal_statuses.setText(_translate("menuWindow", "Новый статус заявки"))
        self.fill_app_statuses.setText(_translate("menuWindow", "Новый статус приложения"))
        self.delete_appeal_statuses.setText(_translate("menuWindow", "Удаление статуса заявки"))
        self.delete_app_statuses.setText(_translate("menuWindow", "Удаление статуса приложения"))
        self.fill_certification_level.setText(_translate("menuWindow", "Новый уровень сертификации"))
        self.delete_certification_level.setText(_translate("menuWindow", "Удалить тип проблемы"))
        self.fill_problem_types.setText(_translate("menuWindow", "Новый тип проблемы"))


def backWindowShow():
    from QtWindows.authorizationWindow import showAuthorizationWindow
    showAuthorizationWindow()
    closeMenuWindow()


def appealStatuses():
    from QtWindows.appealStatusesWindow import showAppealStatusesWindow
    showAppealStatusesWindow()
    closeMenuWindow()


def appStatuses():
    from QtWindows.appStatusesWindow import showAppStatusesWindow
    showAppStatusesWindow()
    closeMenuWindow()


def certificationLevels():
    from QtWindows.certificationLevelsWindow import showCertificationLevelsWindow
    showCertificationLevelsWindow()
    closeMenuWindow()


def fill_appeal_statuses():
    from QtWindows.fill_appeal_statuses_Window import show_fill_appeal_statuses_Window
    show_fill_appeal_statuses_Window()
    closeMenuWindow()


def fill_problem_types():
    from QtWindows.fill_problem_types_Window import show_fill_problem_types_Window
    show_fill_problem_types_Window()
    closeMenuWindow()

def fill_certification_level():
    from QtWindows.fill_certification_level_Window import show_fill_certification_level_Window
    show_fill_certification_level_Window()
    closeMenuWindow()

def fill_app_statuses():
    from QtWindows.fill_app_statuses_Window import show_fill_app_statuses_Window
    show_fill_app_statuses_Window()
    closeMenuWindow()


def delete_appeal_statuses():
    from QtWindows.delete_appeal_statuses_Window import show_delete_appeal_statuses_Window
    show_delete_appeal_statuses_Window()
    closeMenuWindow()

def delete_problem_type():
    from QtWindows.delete_problem_type_Window import show_delete_problem_type_Window
    show_delete_problem_type_Window()
    closeMenuWindow()

def delete_app_statuses():
    from QtWindows.delete_app_statuses_Window import show_delete_app_statuses_Window
    show_delete_app_statuses_Window()
    closeMenuWindow()


def showMenuWindow():
    global menuWindow
    menuWindow = QtWidgets.QDialog()
    ui = Ui_menuWindow()
    ui.setupUi(menuWindow)
    menuWindow.show()


def closeMenuWindow():
    menuWindow.close()
